### PR TITLE
Convert to using git-subtree for ansible-pcp sync-up

### PR DESCRIPTION
**Pull request by natoscott**
Abandon the attempt to have ansible-pcp as a standalone
dependency, after difficulties with both automation hub
and CI.  Instead, use a git subtree for ease of syncing
commits from upstream ansible-pcp repository.  Strategy
used now is consistent with the way upstream PCP itself
manages external dependencies so we have confidence
this will work well.  Updates are done as follows, from
the top level of the metrics repo:

```
git subtree pull \
    --prefix vendor/github.com/performancecopilot/ansible-pcp \
    https://github.com/performancecopilot/ansible-pcp.git HEAD \
    --squash
```

Some minor documentation improvements here also and the
MIT license text is made to match up between repos, but
there's no deep and meaningful changes there.

### CODE REVIEW

**Comment by richm** [comment]
please include some sort of README-devel.md or similar to inform developers about how to sync with the upstream ansible-pcp e.g. how to install git subtree, how to use it, which commit/tag to sync from, etc.
Can this sync be automated?  It would be great if a commit or a tag of ansible-pcp triggered a git subtree update of the metrics role.  Or even a nightly sync.  I do something like this for the ansible execution environment container image - see https://github.com/linux-system-roles/ee_linux_system_roles/blob/main/.github/workflows/nightly-update-and-trigger.yml

**Comment by richm** [comment]
also please check out the errors e.g. from rhel-8-y (rhel 8.6) ansible 2.9:
```
TASK [/tmp/tmpjmj_cudr/vendor/github.com/performancecopilot/ansible-pcp/roles/bpftrace : Install needed bpftrace metrics packages] ***
task path: /tmp/tmpjmj_cudr/vendor/github.com/performancecopilot/ansible-pcp/roles/bpftrace/tasks/main.yml:27
Tuesday 30 November 2021  22:59:04 +0000 (0:00:00.021)       0:00:04.133 ****** 
fatal: [/cache/rhel-8-y.qcow2]: FAILED! => {
    "changed": false,
    "failures": [],
    "rc": 1,
    "results": []
}

MSG:

Depsolve Error occured: 
 Problem 1: package bpftrace-0.12.1-3.el8.x86_64 requires libbcc.so.0()(64bit), but none of the providers can be installed
  - conflicting requests
  - nothing provides libclang-cpp.so.12()(64bit) needed by bcc-0.19.0-4.el8.x86_64
 Problem 2: package pcp-pmda-bpftrace-5.3.5-1.el8.x86_64 requires bpftrace >= 0.9.2, but none of the providers can be installed
  - package bpftrace-0.12.1-3.el8.x86_64 requires libbcc.so.0()(64bit), but none of the providers can be installed
  - conflicting requests
  - nothing provides libclang-cpp.so.12()(64bit) needed by bcc-0.19.0-4.el8.x86_64
```
maybe this is due to missing/mismatched package updates in rhel 8.6, not sure

**Comment by natoscott** [comment]
> maybe this is due to missing/mismatched package updates in rhel 8.6, not sure

Yep, saw that (also some Fedora issues, workin' on those) - I believe the 8.6 issue is outside of PCP and the metrics role, seems to be a clang version issue - I'm seeking more information there though.

**Comment by natoscott** [comment]
> [...]  inform developers about how to sync with the upstream ansible-pcp e.g. how to install git subtree, how to use it, which commit/tag to sync from, etc. Can this sync be automated? It would be great if a commit or a tag of ansible-pcp triggered a git subtree update of the metrics role. Or even a nightly sync.

I went with the nightly sync like ee_linux_system_roles for now - which also serves to document the process I guess - noone should need to do this manually.

**Comment by natoscott** [comment]
@richm All of the ansible-2.12 cases in CI failure - I'm pretty sure its unrelated to this change, and seems to be something to do with that version/setup re-starting all the tests once again, after they've usually all passed, except this time with an extra 'metrics/' in each test case path compared to the ansible-2.9 equivalent cases ...?  Very odd that one.

**Comment by natoscott** [comment]
Jan has confirmed the bpf CI failures are related to latest RHEL composes and unrelated to changes here.
```
<jkurik> a few days back I reported https://bugzilla.redhat.com/show_bug.cgi?id=2026857
<jkurik> should be fixed, when you install bcc-0.19.0-5.el8 (not in compose yet, afaik)
```

**Comment by richm** [comment]
what about the rhel-x/ansible-2.9 failure:
```
pminfo: Cannot connect to PMCD on host "pcp://127.0.0.1?username=pcptest&password=t;dlen;dle": IPC protocol failure
```
?  Is this a known failure because there are some missing/mismatched updates on rhel9?

**Comment by richm** [comment]
> @richm All of the ansible-2.12 cases in CI failure - I'm pretty sure its unrelated to this change, and seems to be something to do with that version/setup re-starting all the tests once again, after they've usually all passed, except this time with an extra 'metrics/' in each test case path compared to the ansible-2.9 equivalent cases ...? Very odd that one.

So that test first runs all of the tests in the "legacy" role format, then converts to collection format, then runs all of the tests again to ensure no regressions due to conversion to collection.

And it seems either our collection conversion procedure doesn't like the new format, or ansible collections don't like the new way subroles are used :-(

**Comment by richm** [comment]
That is - the conversion to collections does not know how to handle
```
 __metrics_role_path: "{{ role_path }}/vendor/github.com/performancecopilot/ansible-pcp/roles"
```
and
```
  include_role:
    name: "{{ __metrics_role_path }}/bpftrace"
```
and making that work correctly in collection format
hmm - @nhosoi any ideas?

**Comment by richm** [comment]
hmm - it is working if I use
```
~/.local/bin/tox -e qemu-ansible-core-2.12 -- --inventory ~/standard-test-roles/inventory/standard-inventory-qcow2 --image-name fedora-34 --collection tests/tests_bz1855539.yml
```
e.g.
```
TASK [/home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp : Set platform/version specific variables] ***
task path: /home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/tasks/main.yml:4
```
so there must be a problem with integration test CI

**Comment by richm** [comment]
ah - the problem is that we do not copy/convert the `vendor/` sub-directory

**Comment by richm** [comment]
The ideal solution would be to do something like this:
```
git subtree pull --prefix roles https://github.com/performancecopilot/ansible-pcp.git --subdir roles HEAD
```
that is - just copy https://github.com/performancecopilot/ansible-pcp `roles/` to `roles/` - but I don't see any support for that with `git subtree` (note that I have no experience with git subtree . . .)

**Comment by nhosoi** [comment]
> ah - the problem is that we do not copy/convert the `vendor/` sub-directory

Sorry for my slow response... Is the issue solved? Yes, in the vendoring code for the legacy roles format, I "vendored" modules in `library`, module_utils in `module_utils`, and filters in `filter_plugins`.

**Comment by richm** [comment]
> > ah - the problem is that we do not copy/convert the `vendor/` sub-directory
> 
> Sorry for my slow response... Is the issue solved? Yes, in the vendoring code for the legacy roles format, I "vendored" modules in `library`, module_utils in `module_utils`, and filters in `filter_plugins`.

I'm working on a more elegant way to solve the metric subrole problem

**Comment by richm** [comment]
wip - https://github.com/linux-system-roles/metrics/pull/99

**Comment by richm** [comment]
[citest bad]

**Comment by natoscott** [comment]
> what about the rhel-x/ansible-2.9 failure:
> 
> pminfo: Cannot connect to PMCD on host "pcp://127.0.0.1?username=pcptest&password=t;dlen;dle": IPC protocol failure
> 
> ? Is this a known failure because there are some missing/mismatched updates on rhel9?

Looks like it was a spurious network connectivity kind of issue - its not a known PCP problem and has passed when re-run today with your latest (unrelated) update.

**Comment by nhosoi** [comment]
Hi @natoscott, @richm, if we run this python code [0], is the subtree automatically pulled as described in the [workflows/subtree.yml](https://github.com/linux-system-roles/metrics/pull/98/files#diff-924b61517a5dd080ea10b598c510a6d9054abca6e1cf46004cc2cba7d9bb125e)?

If not, could there be an easy way to do so, for instance, by setting clone_args to something like `-s subtree SUBTREE_NAME`??? Thanks!

[0]
```
        cmd = gluetool.utils.Command(['git', 'clone'], logger=logger)
        cmd.options += clone_args or self.clone_args
        cmd.options += [
            clone_url,
            actual_path
        ]
```

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
> Hi @natoscott, @richm, if we run this python code [0], is the subtree automatically pulled as described in the [workflows/subtree.yml](https://github.com/linux-system-roles/metrics/pull/98/files#diff-924b61517a5dd080ea10b598c510a6d9054abca6e1cf46004cc2cba7d9bb125e)?
> 
> If not, could there be an easy way to do so, for instance, by setting clone_args to something like `-s subtree SUBTREE_NAME`??? Thanks!
> 
> [0]
> 
> ```
>         cmd = gluetool.utils.Command(['git', 'clone'], logger=logger)
>         cmd.options += clone_args or self.clone_args
>         cmd.options += [
>             clone_url,
>             actual_path
>         ]
> ```

I don't see a `-s` or `--subtree` option for git clone (git 2.31.1)

I think git subtree is the best option for now because it preserves the git history from the source.

**Comment by nhosoi** [comment]
Thanks, @richm.
> I think git subtree is the best option for now because it preserves the git history from the source.

That means we need to add the support for git subtree to baseos ci, I'd guess...

**Comment by richm** [comment]
> Thanks, @richm.
> 
> > I think git subtree is the best option for now because it preserves the git history from the source.
> 
> That means we need to add the support for git subtree to baseos ci, I'd guess...

No, I don't think so.  The git subtree pull will only be used by developers to update the code in the git repo.  This isn't like a git submodule where you have to specify `--recurse-submodules` or something like that - doing `git subtree pull` and `git push` means that the code is committed to the repo - it isn't a "pointer" like a submodule.

**Comment by nhosoi** [comment]
Thanks for the clarification, @richm. Soooo relieved to hear that.

**Pull request merged**
