### PR TITLE
fix: add leading triple-hyphen to all github workflow files

### PR DESCRIPTION
**Pull request by natoscott**
Seems to resolve a github actions lint-style warning.

### CODE REVIEW

**Comment by spetrosi** [comment]
This will be overwritten the next time we run automation from https://github.com/linux-system-roles/.github/. We need to make ansible-lint ignore files in hidden folders.

**Comment by natoscott** [comment]
Yeah, I don't think it was ansible-lint complaining but something within the github workflow UI that was producing these warnings.

**Comment by natoscott** [comment]
> This will be overwritten the next time we run automation from https://github.com/linux-system-roles/.github/. We need to make ansible-lint ignore files in hidden folders. Or just ignore `.github`.

Should this automation step produce new files with the expected yaml document start?

**Comment by natoscott** [comment]
@spetrosi awesome, thanks!

**Pull request merged**
