### PR TITLE
Transition to using the performancecopilot.metrics collection

### PR DESCRIPTION
**Pull request by natoscott**
Drop the local embedded roles from performancecopilot.metrics
and instead use the collection as nature intended now that it
exists in all the places we need it (Fedora, RHEL, Galaxy and
shortly Automation Hub).

### CODE REVIEW

**Comment by richm** [comment]
I guess the next step is to figure out how/where to specify the dependency on performancecopilot.metrics . . .

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest pending]

**Comment by natoscott** [comment]
This approach has been superceded by #98

**Pull request closed without merging**
