### PR TITLE
Do not merge: CI Test failures in RHEL-9

### PR DESCRIPTION
**Pull request by jharuda**

### CODE REVIEW

**Comment by jharuda** [comment]
@andreasgerstmayr 
I am getting an error for RHEL-9. Do you please know what is current state of `cyrus-sasl-scram available` in RHEL-9?

Log:
TASK [/tmp/tmpx2faedq6/roles/pcp : Install authentication packages] ************
task path: /tmp/tmpx2faedq6/roles/pcp/tasks/main.yml:18
fatal: [/cache/rhel-x.qcow2]: FAILED! => {"changed": false, "failures": ["No package cyrus-sasl-scram available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Pull request closed without merging**
