### PR TITLE
[WIP] Update metrics role structure and add pcp role

### PR DESCRIPTION
**Pull request by sradco**

### CODE REVIEW

**Comment by natoscott** [comment]
@sradco @pcahyna I've been working on the new version of linux-system-roles/metrics and have the basics working now, based on our new (internal) list of requirements.  As we discussed some time back it is essentially a rewrite.

This is based on current PCP (v5), and the current linux-system-roles/template repo - plenty has changed in both PCP and linux-system-roles since the original metrics work you and Lukas did a couple of years back.  This old PR is no longer needed for example.

What's the best way to approach this?  Would you like a PR against this repo with the new version?  Or shall we start afresh completely, cloning from the template repo, such that we can do git pulls (or at least direct comparisons) from there as the template moves ahead over time?

Thanks!

**Comment by richm** [comment]
> What's the best way to approach this? Would you like a PR against this repo with the new version? 

Yes, I think that would be fine.

> Or shall we start afresh completely, cloning from the template repo, such that we can do git pulls (or at least direct comparisons) from there as the template moves ahead over time?

If your PR has one or more commits that updates the template files to the latest version, then we can keep the template files in metrics in sync with changes to the template using our sync-template.sh script - https://github.com/linux-system-roles/auto-maintenance/

**Comment by natoscott** [comment]
> > What's the best way to approach this? Would you like a PR against this repo with the new version?
> 
> Yes, I think that would be fine.
> 
> > Or shall we start afresh completely, cloning from the template repo, such that we can do git pulls (or at least direct comparisons) from there as the template moves ahead over time?
> 
> If your PR has one or more commits that updates the template files to the latest version, then we can keep the template files in metrics in sync with changes to the template using our sync-template.sh script - https://github.com/linux-system-roles/auto-maintenance/

Ah, good to know about - thanks Rich.

@sradco any other thoughts / preferences here?

**Comment by sradco** [comment]
> > > What's the best way to approach this? Would you like a PR against this repo with the new version?
> > 
> > 
> > Yes, I think that would be fine.
> > > Or shall we start afresh completely, cloning from the template repo, such that we can do git pulls (or at least direct comparisons) from there as the template moves ahead over time?
> > 
> > 
> > If your PR has one or more commits that updates the template files to the latest version, then we can keep the template files in metrics in sync with changes to the template using our sync-template.sh script - https://github.com/linux-system-roles/auto-maintenance/
> 
> Ah, good to know about - thanks Rich.
> 
> @sradco any other thoughts / preferences here?

@natoscott I think the code here is really outdated, so either can work. If sarting from fresh makes it easier for you for maintenance I don't think it should be a problem.

**Comment by natoscott** [comment]
@richm @sradco @pcahyna great, thanks all - I'll stick with making a PR to this repo since I guess that'll be simplest.

I'll drop the existing content in one commit, and then introduce the new template-repo-based metrics role that uses PCP and Grafana under the covers.

This earlier PR can be closed now BTW, but I don't seem to have permissions to do that.

**Comment by natoscott** [comment]
@richm @sradco @pcahyna https://github.com/linux-system-roles/metrics/pull/10

**Comment by natoscott** [comment]
This is now superceded by the revised metrics role from  PR #10

**Pull request closed without merging**
