### PR TITLE
RHELPLAN-46757 - bug with current implementation of platform/version …

### PR DESCRIPTION
**Pull request by nhosoi**
…specific vars/tasks file include/import

- Adding the full path "{{ role_path }}/vars" to the platform specific var file.
- Replacing '-' with '_' in the file name setup-{RedHat,Debian}.yml.

### CODE REVIEW

**Comment by nhosoi** [comment]
Let me double-check that the metrics role does not support rhel-7...
```
linux-system-roles-test/rhel-7
Testing /tmp/tmpwn7dq112/tests/tests_custom.yml...FAILURE
TASK [linux-system-roles.metrics : Ensure scalable query service is running and enabled on boot] ***
task path: /tmp/tmpwn7dq112/tasks/redis.yml:4
fatal: [/cache/rhel-guest-image-7.8-41.x86_64.qcow2]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}
```

**Comment by richm** [comment]
> Let me double-check that the metrics role does not support rhel-7...
> 
> ```
> linux-system-roles-test/rhel-7
> Testing /tmp/tmpwn7dq112/tests/tests_custom.yml...FAILURE
> TASK [linux-system-roles.metrics : Ensure scalable query service is running and enabled on boot] ***
> task path: /tmp/tmpwn7dq112/tasks/redis.yml:4
> fatal: [/cache/rhel-guest-image-7.8-41.x86_64.qcow2]: FAILED! => {"changed": false, "msg": "Could not find the requested service redis: host"}
> ```

I think that is a bug that @natoscott is working on

**Comment by nhosoi** [comment]
Thanks for your reviews and comments, @richm.

**Comment by natoscott** [comment]
> I think that is a bug that @natoscott is working on

Hmm, I thought this was fixed.  Maybe this is still needed...?

```
diff --git a/tasks/main.yml b/tasks/main.yml
index b078614..e0fa683 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -34,7 +34,11 @@
 - include_tasks: pcp.yml
 
 - include_tasks: redis.yml
-  when: metrics_query_service | bool
+  when:
+    - metrics_query_service | bool
+    - __metrics_packages_query | d([])
 
 - include_tasks: grafana.yml
-  when: metrics_graph_service | bool
+  when:
+    - metrics_graph_service | bool
+    - __metrics_packages_graph | d([])
```

The (optional) graph and query services are not be available on RHEL 7 as there's no packages there to provide the functionality, but the rest of the role will work correctly.

**Comment by nhosoi** [comment]
> > I think that is a bug that @natoscott is working on
> 
> Hmm, I thought this was fixed. Maybe this is still needed...?

+1
@natoscott, I verified your patch made the CI tests pass.

**Comment by richm** [comment]
This brings up a broader question about how to handle features that are only available on some platforms.  @pcahyna is there prior art for this?

As a user, if I specify `metrics_query_service: true` in my inventory, and I am managing an environment with mixed rhel and fedora, what should happen?  Should the playbook run have a hard failure on rhel7 hosts?  If so, do I have to design my inventory in such a way (e.g. host vars, group vars) that `metrics_query_service: true` is only defined for fedora hosts?
Alternately - should installation silently skip rhel hosts, meaning that I have an environment where some hosts are using the query service and some are not, and I may not be aware that some of the hosts are not using the query service?

**Comment by nhosoi** [comment]
I see. If I set metrics_query_service and metrics_graph_service to yes and those services are not supported, I'd like to see a failure. (It'd be nice if I could have a little more informative message than "Could not find the requested service redis: host". :)

Plus, in that case, tests_custom.yml is supposed to catch the exception something like this? (Since the exception occurs only on {RedHat,CentOS}-7, it requires the additional condition, though...)
https://github.com/linux-system-roles/storage/blob/master/tests/tests_lvm_errors.yml#L27-L49

**Comment by richm** [comment]
> I see. If I set metrics_query_service and metrics_graph_service to yes and those services are not supported, I'd like to see a failure. (It'd be nice if I could have a little more informative message than "Could not find the requested service redis: host". :)

+1 - but I'd like to know if we have a precedent in system roles already for this sort of situation that we should follow

> 
> Plus, in that case, tests_custom.yml is supposed to catch the exception something like this? (Since the exception occurs only on {RedHat,CentOS}-7, it requires the additional condition, though...)
> https://github.com/linux-system-roles/storage/blob/master/tests/tests_lvm_errors.yml#L27-L49

or tests_custom.yml could be skipped on rhel/centos 7

**Comment by nhosoi** [comment]
> > Plus, in that case, tests_custom.yml is supposed to catch the exception something like this? (Since the exception occurs only on {RedHat,CentOS}-7, it requires the additional condition, though...)
> > https://github.com/linux-system-roles/storage/blob/master/tests/tests_lvm_errors.yml#L27-L49
> 
> or tests_custom.yml could be skipped on rhel/centos 7

Ah, that sounds much easier (unless we want to check it successfully fails... I guess we'd better wait for the input from @pcahyna.)

**Comment by natoscott** [comment]
@nhosoi @richm @pcahyna I tend to agree - would this alternate patch be the way to go then...?
I'll try that for now, but let me know if there's still better ways to tackle this.

```
diff --git a/tests/tests_custom.yml b/tests/tests_custom.yml
index 6a2e42b..152ed36 100644
--- a/tests/tests_custom.yml
+++ b/tests/tests_custom.yml
@@ -10,3 +10,6 @@
         metrics_retention_days: 5
         metrics_graph_service: yes
         metrics_query_service: yes
+  when:
+    - __metrics_packages_query | d([])
+    - __metrics_packages_graph | d([])
diff --git a/tests/tests_graph.yml b/tests/tests_graph.yml
index 2160567..5dbd0aa 100644
--- a/tests/tests_graph.yml
+++ b/tests/tests_graph.yml
@@ -7,3 +7,5 @@
     - role: linux-system-roles.metrics
       vars:
         metrics_graph_service: yes
+  when:
+    - __metrics_packages_graph | d([])
diff --git a/tests/tests_query.yml b/tests/tests_query.yml
index bafc8d7..03cc18c 100644
--- a/tests/tests_query.yml
+++ b/tests/tests_query.yml
@@ -6,4 +6,6 @@
   roles:
     - role: linux-system-roles.metrics
       vars:
-        metrics_graph_service: yes
+        metrics_query_service: yes
+  when:
+    - __metrics_packages_query | d([])
```

**Pull request merged**
