### PR TITLE
ansible-lint 6.x fixes

### PR DESCRIPTION
**Pull request by richm**
All tasks and plays must be named
All task names must begin with uppercase letter
No spaces in brackets and braces
Use spaces in jinja pipelines
Use `true`/`false` instead of `yes`/`no`
The `vars` and `when` should come before block/rescue/always
Use `set -o pipefail` in `shell`

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
@natoscott the tests are failing like this:
```
TASK [/home/rmeggins/linux-system-roles/metrics/tests/roles/linux-system-roles.metrics/roles/pcp : Ensure extra performance rules are installed for targeted hosts] ***
task path: /home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/tasks/pmie.yml:24
...
failed: [/home/rmeggins/.cache/linux-system-roles/rhel-8-y.qcow2] (item=filesys/vfs_rules) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "filesys/vfs_rules"
}

MSG:

Could not find or access 'files/filesys/vfs_rules'
Searched in:
        /home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/files/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/tests/roles/linux-system-roles.metrics/files/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/tests/roles/linux-system-roles.metrics/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/tasks/files/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/tasks/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/tests/files/files/filesys/vfs_rules
        /home/rmeggins/linux-system-roles/metrics/tests/files/filesys/vfs_rules on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```
has vfs_rules been dropped or renamed as one of the pmieconf rules?

**Comment by richm** [comment]
I tried this:
```
--- a/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/vars/main.yml
+++ b/vendor/github.com/performancecopilot/ansible-pcp/roles/pcp/vars/main.yml
@@ -27,6 +27,7 @@ __pcp_pmieconf_groups:
   - network
   - power
   - zeroconf
+  - filesys
 
 __pcp_pmieconf_rules:
   - network/tcplistenoverflows
```
but that didn't help

**Comment by natoscott** [comment]
@richm just back from holidays today, will take a look asap... the vfs_rules is new (not dropped), we must have missed something somewhere though

**Comment by richm** [comment]
ok - I'm going to commit these changes as I don't believe they have introduced any regressions

**Pull request merged**
