### PR TITLE
 Add check for non-inclusive language

### PR DESCRIPTION
**Pull request by nhosoi**
Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml

CHANGELOG.md - cleanup non-inclusive words.

Note: The file name `tests/tests_sanity_*.yml` is preferable not to include `sanity` in it. We set the severity level of `sanity` to `warning` at https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml#L59. So, they are not reported as an error for now. What should we do on this issue? Shall we leave them as they are or rename them to something else not including `sanity`?

Second note: To skip the warnings, we have to apply this patch (https://github.com/get-woke/woke/pull/252) to `woke`. Is it ok to do it in this pr?

### CODE REVIEW

**Comment by nhosoi** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Review by natoscott — CHANGES_REQUESTED** [review]
@nhosoi thanks for looking into this - I'd be happy with switching to phrasing like 'confidence test' here instead of sanity, which would simplify this change I think?

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest]

**Comment by nhosoi** [comment]
@natoscott, @richm, could there be anything else we should update this pr to make sure the inclusive language is ensured (=~ `woke` does not return an error)? Thanks!

**Comment by nhosoi** [comment]
@natoscott, is it ok with you to merge this pr, too?

**Review by natoscott — APPROVED** [review]
@nhosoi looks good - thanks for working on it!

**Pull request merged**
