### PR TITLE
RHELPLAN-56582 - sync collections related changes from template to metrics role

### PR DESCRIPTION
**Pull request by nhosoi**
- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.

### CODE REVIEW

**Comment by natoscott** [comment]
>     * Adding .travis/runcollection.sh.

Looks like this downloads the role-to-collection script and then runs it to convert the role to a collection, in a tox test directory?

Is this a temporary change or is it the long-term plan when it comes to converting roles to collections?  I was expecting we'd see roles (like metrics) converted to collections once, that change would then be committed, and then forever after we'd operate under the collection repo layout.

**Comment by nhosoi** [comment]
> > ```
> > * Adding .travis/runcollection.sh.
> > ```
>
> Looks like this downloads the role-to-collection script and then runs it to convert the role to a collection, in a tox test directory?

Yes, that's what runcollection.sh does.

> Is this a temporary change or is it the long-term plan when it comes to converting roles to collections? I was expecting we'd see roles (like metrics) converted to collections once, that change would then be committed, and then forever after we'd operate under the collection repo layout.

In the long run, we will be migrating to the collections layout completely. But for a while we decided that each team develops their role in the current linux-system-roles sub-repository, and we run the collection conversion tool to generate the collection format to push to Automation Hub or Galaxy. So, until the migration time is determined, enhancements and bug fixes are to be made in the current repository.
@richm, @pcahyna, do we have some estimation when it'd be?

**Comment by richm** [comment]
> @richm, @pcahyna, do we have some estimation when it'd be?

I think as long as we have to support EL7, we will need to support the old roles format.  And it is more difficult to go from collections to roles than it is from roles to collections.

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
Thank you for your reviewing the PR, @natoscott and @richm. Merged.

**Pull request merged**
